apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aonic-ui
  annotations:
    github.com/project-slug: Eswaraiahsapram/aonic-ui
spec:
  type: other
  lifecycle: unknown
  owner: user:default/eswaraiahsapram
